name: "Hello World"
description: "Greet someone"
inputs:
  to:
    description: "To"
    required: true
  token:
    description: "Token"
    required: true
  args:
    description: "arg"
    required: true
runs:
  using: "composite"
  steps:
    - run: echo Hello Panda Script.
      shell: bash
    - run: |
        source src/health.sh
        panda_health_check ${{ inputs.to }}
      shell: bash