on: [push]

jobs:
  hello_world_job:
    name: A job to say hello
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install panda script
        uses: DeeTeeeee/tele-action@main
        with:
          script: panda_health_check